// @agentnexus/next - Stub for Agent-Native middleware
// Future: full implementation with headers, llms.txt generation, etc.

export interface AgentNativeConfig {
  enableMarkdown?: boolean;
  generateLlmsTxt?: boolean;
  apiCatalogPath?: string;
}

export function agentNativeMiddleware(config: AgentNativeConfig = {}) {
  return async (req: any, res: any, next: any) => {
    // Stub: Set basic agent-friendly headers
    res.setHeader('X-Agent-Native', 'v0.1');
    res.setHeader('Link', '</llms.txt>; rel="agent-llms"');
    
    if (config.enableMarkdown && req.headers.accept?.includes('text/markdown')) {
      // Would convert to MD in real impl
    }
    
    next?.();
  };
}

export function generateLlmsTxt(siteData: any) {
  return `# LLMs.txt stub generated by @agentnexus/next\n# See AGENT-NATIVE-STANDARD.md`;
}
